services:
  - type: web
    name: QUEEN VENOM-MD 
    env: node
    branch: main
    repo: https://github.com/DRK-S-TEN/KLAUS-MD-.git
    buildCommand: yarn install
    startCommand: yarn start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: STATUS_VIEW_SEEN
        value: true
      - key: MODE
        value: public
      - key: AUTO_REACT
        value: true
